In [1]:
import pandas as pd

In [2]:
import numpy as np

In [4]:
data = pd.read_csv('play_tennis.csv')

In [5]:
data.head()

  day   outlook  temp humidity    wind play
0  D1     Sunny   Hot     High    Weak   No
1  D2     Sunny   Hot     High  Strong   No
2  D3  Overcast   Hot     High    Weak  Yes
3  D4      Rain  Mild     High    Weak  Yes
4  D5      Rain  Cool   Normal    Weak  Yes

In [7]:
data.drop(columns=['day'],inplace=True)

In [8]:
data

     outlook  temp humidity    wind play
0      Sunny   Hot     High    Weak   No
1      Sunny   Hot     High  Strong   No
2   Overcast   Hot     High    Weak  Yes
3       Rain  Mild     High    Weak  Yes
4       Rain  Cool   Normal    Weak  Yes
5       Rain  Cool   Normal  Strong   No
6   Overcast  Cool   Normal  Strong  Yes
7      Sunny  Mild     High    Weak   No
8      Sunny  Cool   Normal    Weak  Yes
9       Rain  Mild   Normal    Weak  Yes
10     Sunny  Mild   Normal  Strong  Yes
11  Overcast  Mild     High  Strong  Yes
12  Overcast   Hot   Normal    Weak  Yes
13      Rain  Mild     High  Strong   No

In [9]:
# training
#look up table(dictionary)

In [10]:
#P(Yes)

In [11]:
data['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [12]:
py = 9/14

In [13]:
pn = 5/14

In [14]:
print(py)

0.6428571428571429

In [15]:
print(pn)

0.35714285714285715

In [16]:
#outlook
pd.crosstab(data['outlook'],data['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [17]:
Pon = 0
Prn = 2/5
Psn = 3/5
Poy = 4/9
Pry = 3/9
Psy = 2/9

In [18]:
#temperature
pd.crosstab(data['temp'],data['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [19]:
PCoolNo = 1/5
PHotNo = 2/5
PMildNo = 2/5
PCoolYes = 3/9
PHotYes = 2/9
PMildYes = 4/9

In [20]:
#Humidity
pd.crosstab(data['humidity'],data['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [21]:
PHighNo = 4/5
PNormalNo = 1/5
PHighYes = 3/9
PNormalYes = 6/9

In [22]:
#wind
pd.crosstab(data['wind'],data['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [23]:
PStrongNo = 3/5
PWeakNo = 2/5
PStrongYes = 3/9
PWeakYes = 6/9

In [26]:
PYes = py*Psy*PHotYes*PHighYes*PWeakYes

In [27]:
print(PYes)

0.007054673721340388

In [28]:
PNo = pn*Psn*PHotNo*PHighNo*PWeakNo

In [29]:
print(PNo)

0.02742857142857143